tomi: 
  eval_method: free-form
  eval_keys: ['alternative container', 'answer']
  delimiter: ''
  timetom: free-form

hitom: 
  eval_method: multiple-choice
  eval_keys: ['choices', 'answer']
  delimiter: ','
  timetom: multiple-choice

opentom:
  eval_method: opentom
  eval_keys: []
  delimiter: ''
  timetom: free-form

exploretom:
  eval_method: free-form
  eval_keys: []
  delimiter: ''
  timetom: free-form

fantom:
  eval_method: multiple-choice
  eval_keys: ['wrong_answer', 'correct_answer']
  delimiter: ''
  timetom: multiple-choice

fantom_long:
  eval_method: multiple-choice
  eval_keys: ['wrong_answer', 'correct_answer']
  delimiter: ''
  timetom: multiple-choice
