vanilla_text: 
  prompt_type: vanilla-text 

cot_text: 
  prompt_type: cot-text

simtom_text:
  prompt_type: simtom-text

masktom_ada_text:
  prompt_type: vanilla-text 
  masktom: True
  representation: text 
  masktom_version: ada

masktom_babbage1_text:
  prompt_type: vanilla-text 
  masktom: True
  representation: text 
  masktom_version: babbage1

masktom_babbage2_text:
  prompt_type: vanilla-text 
  masktom: True
  representation: text 
  masktom_version: babbage2

masktom_curie1_text:
  prompt_type: vanilla-text 
  masktom: True
  representation: text 
  masktom_version: curie1

masktom_curie2_text:
  prompt_type: vanilla-text 
  masktom: True
  representation: text 
  masktom_version: curie2

masktom_ada_markdown:
  prompt_type: code 
  masktom: True
  representation: markdown 
  masktom_version: ada

masktom_babbage1_markdown:
  prompt_type: code 
  masktom: True
  representation: markdown 
  masktom_version: babbage1

masktom_babbage2_markdown:
  prompt_type: code 
  masktom: True
  representation: markdown 
  masktom_version: babbage2

masktom_curie1_markdown:
  prompt_type: code 
  masktom: True
  representation: markdown 
  masktom_version: curie1

masktom_curie2_markdown:
  prompt_type: code 
  masktom: True
  representation: markdown 
  masktom_version: curie2
