llama3-8b: [
  'hf',
  '/scratch/prj/charnu/seacow_hf_cache/llama3.1-8b',
  './configs/generation_config.yml',
  16,
]

llama3-70b: [
  'hf',
  '/scratch_tmp/prj/inf_llmcache/hf_cache/models--meta-llama--Llama-3.3-70B-Instruct/snapshots/38ff4e01a70559264c95945aa04b900a11e68422',
  './configs/generation_config.yml',
  16,
]

gemma9: [
  'hf',
  '/scratch_tmp/prj/inf_llmcache/hf_cache/models--google--gemma-2-9b-it/snapshots/11c9b309abf73637e4b6f9a3fa1e92e615547819',
  './configs/generation_config.yml',
  16,
]

gemma27: [
  'hf',
  '/scratch_tmp/prj/inf_llmcache/hf_cache/models--google--gemma-2-27b-it/snapshots/aaf20e6b9f4c0fcf043f6fb2a2068419086d77b0',
  './configs/generation_config.yml',
  16,
]

gpt35: [
  'gpt', 
  '',
  '~/hainiu_openai_gpt35_1106.config',
  0,
]

gpt4: [
  'gpt', 
  '',
  '~/hainiu_openai_gpt4.config',
  0,
]

qwen1.5: [
  'hf',
  '/scratch_tmp/prj/inf_llmcache/hf_cache/models--Qwen--Qwen2.5-1.5B-Instruct/snapshots/989aa7980e4cf806f80c7fef2b1adb7bc71aa306',
  './configs/generation_config.yml',
  16,
]

qwen3: [
  'hf',
  '/scratch_tmp/prj/inf_llmcache/hf_cache/models--Qwen--Qwen2.5-3B-Instruct/snapshots/aa8e72537993ba99e69dfaafa59ed015b17504d1',
  './configs/generation_config.yml',
  16,
]

qwen7: [
  'hf',
  '/scratch_tmp/prj/inf_llmcache/hf_cache/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/bb46c15ee4bb56c5b63245ef50fd7637234d6f75',
  './configs/generation_config.yml',
  16,
]

qwen14: [
  'hf',
  '/scratch_tmp/prj/inf_llmcache/hf_cache/models--Qwen--Qwen2.5-14B-Instruct/snapshots/cf98f3b3bbb457ad9e2bb7baf9a0125b6b88caa8',
  './configs/generation_config.yml',
  16,
]

qwen32: [
  'hf',
  '/scratch_tmp/prj/inf_llmcache/hf_cache/models--Qwen--Qwen2.5-32B-Instruct/snapshots/5ede1c97bbab6ce5cda5812749b4c0bdf79b18dd',
  './configs/generation_config.yml',
  16,
]

qwen72: [
  'hf',
  '/scratch_tmp/prj/charnu/seacow_hf_cache/models--unsloth--Qwen2.5-72B-Instruct-bnb-4bit/snapshots/95cde7b0316fd420d6fb7496c41f56fb9a1711d3',
  './configs/generation_config.yml',
  16,
]
