llama3-8b:
  script_path: "../vllm_servers/llama3-8b-server.sh"
  base_url: "http://localhost:8888/v1"
  api_key: "seacow"

llama3-70b:
  script_path: "../vllm_servers/llama3-70b-server.sh"
  base_url: "http://localhost:8888/v1"
  api_key: "seacow"

qwen1.5:
  script_path: "../vllm_servers/tmp_qwen3-server.sh"
  base_url: "http://localhost:8888/v1"
  api_key: "seacow"

qwen3:
  script_path: "../vllm_servers/tmp_qwen3-server.sh"
  base_url: "http://localhost:8888/v1"
  api_key: "seacow"

qwen7:
  script_path: "../vllm_servers/tmp_qwen7-server.sh"
  base_url: "http://localhost:8888/v1"
  api_key: "seacow"

qwen14:
  script_path: "../vllm_servers/tmp_qwen14-server.sh"
  base_url: "http://localhost:8888/v1"
  api_key: "seacow"

qwen32:
  script_path: "../vllm_servers/tmp_qwen32-server.sh"
  base_url: "http://localhost:8888/v1"
  api_key: "seacow"

qwen72:
  script_path: "../vllm_servers/tmp_qwen72-server.sh"
  base_url: "http://localhost:8888/v1"
  api_key: "seacow"

gemma9:
  script_path: "../vllm_servers/tmp_gemma9-server.sh"
  base_url: "http://localhost:8888/v1"
  api_key: "seacow"

gemma27:
  script_path: "../vllm_servers/tmp_gemma27-server.sh"
  base_url: "http://localhost:8888/v1"
  api_key: "seacow"

mixtral:
  script_path: "../vllm_servers/mixtral-server.sh"
  base_url: "http://localhost:8000/v1"
  api_key: "seacow"

mixtral:
  script_path: ""
  base_url: ""
  api_key: ""
